// sidepanel.js — Intent & Orchestration surfaces

// ── State ────────────────────────────────────────────────────────────────────
let domContext = null;        // captured from content script
let pendingPatch = null;      // generated by Ollama, awaiting review
let inspectorActive = false;
let hasAppliedPatch = false;
let activeTabId = null;

// ── DOM refs ─────────────────────────────────────────────────────────────────
const chat          = document.getElementById("chat");
const contextBar    = document.getElementById("context-bar");
const input         = document.getElementById("complaint-input");
const btnSend       = document.getElementById("btn-send");
const btnInspector  = document.getElementById("btn-inspector");
const btnClearCtx   = document.getElementById("btn-clear-ctx");
const btnUndo       = document.getElementById("btn-undo");
const sandbox       = document.getElementById("preview-sandbox");
const patchPreview  = document.getElementById("patch-preview");
const btnAccept     = document.getElementById("btn-accept");
const btnReject     = document.getElementById("btn-reject");
const ollamaStatus  = document.getElementById("ollama-status");

// ── Init ─────────────────────────────────────────────────────────────────────
(async function init() {
  // Get current tab id
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  if (tab) activeTabId = tab.id;

  // Check if Ollama is running
  pingOllama();

  // Restore session context if any
  const stored = await chrome.storage.session.get(["domContext"]);
  if (stored.domContext) setContext(stored.domContext);
})();

// ── Ollama health check ───────────────────────────────────────────────────────
async function pingOllama() {
  try {
    const r = await fetch("http://localhost:11434/api/tags", { signal: AbortSignal.timeout(2000) });
    if (r.ok) {
      ollamaStatus.classList.remove("offline");
      ollamaStatus.title = "Ollama running";
    }
  } catch {
    ollamaStatus.classList.add("offline");
    ollamaStatus.title = "Ollama not reachable — start with: ollama serve";
    addMessage("system", "⚠️ Ollama not detected. Run: ollama serve");
  }
}

// ── Message listener from background ─────────────────────────────────────────
chrome.runtime.onMessage.addListener((message) => {
  if (message.type === "DOM_CONTEXT_READY") {
    setContext(message.payload);
    addMessage("system", `📌 Captured: <${message.payload.tagName}> — "${message.payload.textContent.slice(0, 60)}..."`);
  }
});

// ── Context helpers ───────────────────────────────────────────────────────────
function setContext(ctx) {
  domContext = ctx;
  contextBar.classList.remove("empty");
  contextBar.textContent = `📎 ${ctx.selector}  ·  <${ctx.tagName}>  ·  ${ctx.pageUrl.slice(0, 40)}…`;
}

function clearContext() {
  domContext = null;
  contextBar.classList.add("empty");
  contextBar.textContent = "No element captured — use Inspector to pick one";
}

// ── Chat helpers ─────────────────────────────────────────────────────────────
function addMessage(role, html) {
  const div = document.createElement("div");
  div.className = `msg ${role}`;
  div.innerHTML = html;
  chat.appendChild(div);
  chat.scrollTop = chat.scrollHeight;
  return div;
}

// ── Send complaint → generate patch ──────────────────────────────────────────
async function handleSend() {
  const complaint = input.value.trim();
  if (!complaint) return;

  addMessage("user", complaint);
  input.value = "";
  btnSend.disabled = true;

  if (!domContext) {
    addMessage("system", "⚠️ No element selected. Click Inspector first, then pick an element.");
    btnSend.disabled = false;
    return;
  }

  const loadingMsg = addMessage("assistant", '<span class="spinner"></span> Generating patch…');

  const response = await chrome.runtime.sendMessage({
    type: "GENERATE_PATCH",
    payload: { userComplaint: complaint, domContext },
  });

  loadingMsg.remove();

  if (!response.ok) {
    addMessage("system", `❌ Error: ${response.error}`);
    btnSend.disabled = false;
    return;
  }

  pendingPatch = response.patch;
  showPatchSandbox(pendingPatch);
  addMessage("assistant", "Patch ready. Review the code above and accept or reject.");
  btnSend.disabled = false;
}

// ── Preview sandbox ───────────────────────────────────────────────────────────
function showPatchSandbox(patch) {
  patchPreview.textContent = patch;
  sandbox.classList.add("visible");
  sandbox.scrollIntoView({ behavior: "smooth", block: "nearest" });
}

function hidePatchSandbox() {
  sandbox.classList.remove("visible");
  pendingPatch = null;
}

// ── Accept patch ──────────────────────────────────────────────────────────────
btnAccept.addEventListener("click", async () => {
  if (!pendingPatch || !activeTabId) return;

  btnAccept.disabled = true;
  const r = await chrome.runtime.sendMessage({
    type: "APPLY_PATCH",
    tabId: activeTabId,
    payload: pendingPatch,
  });

  if (r.ok) {
    addMessage("system", "✅ Patch applied. Click ↩ Undo to revert.");
    hasAppliedPatch = true;
    btnUndo.classList.add("visible");
  } else {
    addMessage("system", `❌ Apply failed: ${r.error}`);
  }

  btnAccept.disabled = false;
  hidePatchSandbox();
});

// ── Reject patch ──────────────────────────────────────────────────────────────
btnReject.addEventListener("click", () => {
  hidePatchSandbox();
  addMessage("system", "↩ Patch rejected. Try rephrasing your complaint.");
});

// ── Undo patch ────────────────────────────────────────────────────────────────
btnUndo.addEventListener("click", async () => {
  if (!activeTabId) return;
  const r = await chrome.runtime.sendMessage({ type: "UNDO_PATCH", tabId: activeTabId });
  if (r.ok) {
    addMessage("system", "↩ Patch removed. Page restored.");
    hasAppliedPatch = false;
    btnUndo.classList.remove("visible");
  }
});

// ── Inspector toggle ──────────────────────────────────────────────────────────
btnInspector.addEventListener("click", async () => {
  if (!activeTabId) return;

  if (!inspectorActive) {
    await chrome.tabs.sendMessage(activeTabId, { type: "START_INSPECTOR" });
    inspectorActive = true;
    btnInspector.classList.add("active");
    btnInspector.textContent = "🔎 Cancel";
    addMessage("system", "Inspector active — click any element on the page.");
  } else {
    await chrome.tabs.sendMessage(activeTabId, { type: "STOP_INSPECTOR" });
    inspectorActive = false;
    btnInspector.classList.remove("active");
    btnInspector.textContent = "🔎 Inspector";
  }
});

// When DOM context arrives, turn off inspector state
chrome.runtime.onMessage.addListener((msg) => {
  if (msg.type === "DOM_CONTEXT_READY") {
    inspectorActive = false;
    btnInspector.classList.remove("active");
    btnInspector.textContent = "🔎 Inspector";
  }
});

// ── Clear context ─────────────────────────────────────────────────────────────
btnClearCtx.addEventListener("click", () => {
  clearContext();
  chrome.storage.session.remove("domContext");
});

// ── Send on Enter (Shift+Enter for newline) ───────────────────────────────────
input.addEventListener("keydown", (e) => {
  if (e.key === "Enter" && !e.shiftKey) {
    e.preventDefault();
    if (!btnSend.disabled) handleSend();
  }
});

btnSend.addEventListener("click", handleSend);
